@startuml
hide empty description
state "State3" as 0
state "State0" as 1
state "State2" as 2
state "State1" as 3
state "Composite State" as 4
4 : Detailed info and complex instructions.
0 --> 1 : rule4
2 --> 0 : rule3
[*] --> 1 : true
1 --> 3 : rule1
3 --> 2 : rule2
0 --> 4 : rule5
4 --> [*] : rule6
@enduml